In [1]:
import pandas as pd

df = pd.read_csv('student-por.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [2]:
X = df[['failures','goout','health']]
y = df['G3']
X

     failures  goout  health
0           0      4       3
1           0      3       3
2           0      2       3
3           0      2       5
4           0      2       5
..        ...    ...     ...
644         1      2       5
645         0      4       1
646         0      1       5
647         0      5       2
648         0      1       5

[649 rows x 3 columns]

In [14]:
import numpy as np
from sklearn.linear_model import Ridge, Lasso

ridge = Ridge(alpha=0)

ridge.fit(X,y);

In [15]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2, include_bias=False)

X_poly = poly.fit_transform(X)
X_poly.shape

(649, 9)

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() 
X_scaled = scaler.fit_transform(X_poly) # 표준점수로 변환
X_scaled[:5]

array([[-0.37430512,  0.69378496, -0.3710422 , -0.27717038, -0.3424015 ,
        -0.3446603 ,  0.58782199,  0.11749022, -0.59976447],
       [-0.37430512, -0.15738033, -0.3710422 , -0.27717038, -0.3424015 ,
        -0.3446603 , -0.33144662, -0.34370626, -0.59976447],
       [-0.37430512, -1.00854562, -0.3710422 , -0.27717038, -0.3424015 ,
        -0.3446603 , -0.98806706, -0.80490273, -0.59976447],
       [-0.37430512, -1.00854562,  1.01290255, -0.27717038, -0.3424015 ,
        -0.3446603 , -0.98806706, -0.1899741 ,  1.1159254 ],
       [-0.37430512, -1.00854562,  1.01290255, -0.27717038, -0.3424015 ,
        -0.3446603 , -0.98806706, -0.1899741 ,  1.1159254 ]])

In [17]:
import numpy as np

alphas = np.logspace(-3,3,200)

In [19]:
ridge_coefs = []
lasso_coefs = []

for alpha in alphas:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_scaled, y)
    ridge_coefs.append(ridge.coef_)

for alpha in alphas:
    lasso = Lasso(alpha=alpha)
    lasso.fit(X_scaled, y)
    lasso_coefs.append(lasso.coef_)